[2024-11-23 11:20:36,884][flwr][WARNING] - Both server and strategy were provided, ignoring strategy
[2024-11-23 11:20:36,884][flwr][INFO] - Starting Flower simulation, config: ServerConfig(num_rounds=2, round_timeout=None)
[2024-11-23 11:20:42,119][flwr][INFO] - Flower VCE: Ray initialized with resources: {'object_store_memory': 3445209907.0, 'node:__internal_head__': 1.0, 'node:192.168.1.62': 1.0, 'CPU': 12.0, 'accelerator_type:G': 1.0, 'GPU': 1.0, 'memory': 6890419815.0}
[2024-11-23 11:20:42,119][flwr][INFO] - Flower VCE: Resources for each Virtual Client: {'num_cpus': 6, 'num_gpus': 0.5}
[2024-11-23 11:20:42,130][flwr][INFO] - Flower VCE: Creating VirtualClientEngineActorPool with 2 actors
[2024-11-23 11:20:42,130][flwr][INFO] - Initializing global parameters
[2024-11-23 11:20:42,130][flwr][INFO] - Requesting initial parameters from one random client
[2024-11-23 11:20:45,530][flwr][ERROR] - Traceback (most recent call last):
  File "/home/namvq/.cache/pypoetry/virtualenvs/niid-bench-orV17zke-py3.10/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 140, in _submit_job
    res = self.actor_pool.get_client_result(self.cid, timeout)
  File "/home/namvq/.cache/pypoetry/virtualenvs/niid-bench-orV17zke-py3.10/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 402, in get_client_result
    return self._fetch_future_result(cid)
  File "/home/namvq/.cache/pypoetry/virtualenvs/niid-bench-orV17zke-py3.10/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 288, in _fetch_future_result
    res_cid, res = ray.get(future)  # type: (str, ClientRes)
  File "/home/namvq/.cache/pypoetry/virtualenvs/niid-bench-orV17zke-py3.10/lib/python3.10/site-packages/ray/_private/auto_init_hook.py", line 24, in auto_init_wrapper
    return fn(*args, **kwargs)
  File "/home/namvq/.cache/pypoetry/virtualenvs/niid-bench-orV17zke-py3.10/lib/python3.10/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "/home/namvq/.cache/pypoetry/virtualenvs/niid-bench-orV17zke-py3.10/lib/python3.10/site-packages/ray/_private/worker.py", line 2524, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(ClientException): [36mray::DefaultActor.run()[39m (pid=77529, ip=192.168.1.62, actor_id=33b8b395ca8c80c1c3a0779601000000, repr=<flwr.simulation.ray_transport.ray_actor.DefaultActor object at 0x7cbd7010f100>)
  File "/home/namvq/.cache/pypoetry/virtualenvs/niid-bench-orV17zke-py3.10/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 179, in get_parameters
    return maybe_call_get_parameters(
  File "/home/namvq/.cache/pypoetry/virtualenvs/niid-bench-orV17zke-py3.10/lib/python3.10/site-packages/flwr/client/client.py", line 197, in maybe_call_get_parameters
    return client.get_parameters(get_parameters_ins)
  File "/home/namvq/.cache/pypoetry/virtualenvs/niid-bench-orV17zke-py3.10/lib/python3.10/site-packages/flwr/client/app.py", line 320, in _get_parameters
    parameters = self.numpy_client.get_parameters(config=ins.config)  # type: ignore
  File "/media/namvq/Data/code_flwr/niid_bench/niid_bench/client_fednova.py", line 53, in get_parameters
    return [val.cpu().numpy() for val in self.net.parameters()]
  File "/media/namvq/Data/code_flwr/niid_bench/niid_bench/client_fednova.py", line 53, in <listcomp>
    return [val.cpu().numpy() for val in self.net.parameters()]
RuntimeError: Can't call numpy() on Tensor that requires grad. Use tensor.detach().numpy() instead.

The above exception was the direct cause of the following exception:

[36mray::DefaultActor.run()[39m (pid=77529, ip=192.168.1.62, actor_id=33b8b395ca8c80c1c3a0779601000000, repr=<flwr.simulation.ray_transport.ray_actor.DefaultActor object at 0x7cbd7010f100>)
  File "/home/namvq/.cache/pypoetry/virtualenvs/niid-bench-orV17zke-py3.10/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 72, in run
    raise ClientException(str(message)) from ex
flwr.simulation.ray_transport.ray_actor.ClientException: 
>>>>>>>A ClientException occurred.('\n\tSomething went wrong when running your client workload.\n\tClient 1 crashed when the DefaultActor was running its workload.\n\tException triggered on the client side: Traceback (most recent call last):\n  File "/home/namvq/.cache/pypoetry/virtualenvs/niid-bench-orV17zke-py3.10/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 60, in run\n    job_results = job_fn()\n  File "/home/namvq/.cache/pypoetry/virtualenvs/niid-bench-orV17zke-py3.10/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 179, in get_parameters\n    return maybe_call_get_parameters(\n  File "/home/namvq/.cache/pypoetry/virtualenvs/niid-bench-orV17zke-py3.10/lib/python3.10/site-packages/flwr/client/client.py", line 197, in maybe_call_get_parameters\n    return client.get_parameters(get_parameters_ins)\n  File "/home/namvq/.cache/pypoetry/virtualenvs/niid-bench-orV17zke-py3.10/lib/python3.10/site-packages/flwr/client/app.py", line 320, in _get_parameters\n    parameters = self.numpy_client.get_parameters(config=ins.config)  # type: ignore\n  File "/media/namvq/Data/code_flwr/niid_bench/niid_bench/client_fednova.py", line 53, in get_parameters\n    return [val.cpu().numpy() for val in self.net.parameters()]\n  File "/media/namvq/Data/code_flwr/niid_bench/niid_bench/client_fednova.py", line 53, in <listcomp>\n    return [val.cpu().numpy() for val in self.net.parameters()]\nRuntimeError: Can\'t call numpy() on Tensor that requires grad. Use tensor.detach().numpy() instead.\n',)

[2024-11-23 11:20:45,530][flwr][ERROR] - [36mray::DefaultActor.run()[39m (pid=77529, ip=192.168.1.62, actor_id=33b8b395ca8c80c1c3a0779601000000, repr=<flwr.simulation.ray_transport.ray_actor.DefaultActor object at 0x7cbd7010f100>)
  File "/home/namvq/.cache/pypoetry/virtualenvs/niid-bench-orV17zke-py3.10/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 179, in get_parameters
    return maybe_call_get_parameters(
  File "/home/namvq/.cache/pypoetry/virtualenvs/niid-bench-orV17zke-py3.10/lib/python3.10/site-packages/flwr/client/client.py", line 197, in maybe_call_get_parameters
    return client.get_parameters(get_parameters_ins)
  File "/home/namvq/.cache/pypoetry/virtualenvs/niid-bench-orV17zke-py3.10/lib/python3.10/site-packages/flwr/client/app.py", line 320, in _get_parameters
    parameters = self.numpy_client.get_parameters(config=ins.config)  # type: ignore
  File "/media/namvq/Data/code_flwr/niid_bench/niid_bench/client_fednova.py", line 53, in get_parameters
    return [val.cpu().numpy() for val in self.net.parameters()]
  File "/media/namvq/Data/code_flwr/niid_bench/niid_bench/client_fednova.py", line 53, in <listcomp>
    return [val.cpu().numpy() for val in self.net.parameters()]
RuntimeError: Can't call numpy() on Tensor that requires grad. Use tensor.detach().numpy() instead.

The above exception was the direct cause of the following exception:

[36mray::DefaultActor.run()[39m (pid=77529, ip=192.168.1.62, actor_id=33b8b395ca8c80c1c3a0779601000000, repr=<flwr.simulation.ray_transport.ray_actor.DefaultActor object at 0x7cbd7010f100>)
  File "/home/namvq/.cache/pypoetry/virtualenvs/niid-bench-orV17zke-py3.10/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 72, in run
    raise ClientException(str(message)) from ex
flwr.simulation.ray_transport.ray_actor.ClientException: 
>>>>>>>A ClientException occurred.('\n\tSomething went wrong when running your client workload.\n\tClient 1 crashed when the DefaultActor was running its workload.\n\tException triggered on the client side: Traceback (most recent call last):\n  File "/home/namvq/.cache/pypoetry/virtualenvs/niid-bench-orV17zke-py3.10/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 60, in run\n    job_results = job_fn()\n  File "/home/namvq/.cache/pypoetry/virtualenvs/niid-bench-orV17zke-py3.10/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 179, in get_parameters\n    return maybe_call_get_parameters(\n  File "/home/namvq/.cache/pypoetry/virtualenvs/niid-bench-orV17zke-py3.10/lib/python3.10/site-packages/flwr/client/client.py", line 197, in maybe_call_get_parameters\n    return client.get_parameters(get_parameters_ins)\n  File "/home/namvq/.cache/pypoetry/virtualenvs/niid-bench-orV17zke-py3.10/lib/python3.10/site-packages/flwr/client/app.py", line 320, in _get_parameters\n    parameters = self.numpy_client.get_parameters(config=ins.config)  # type: ignore\n  File "/media/namvq/Data/code_flwr/niid_bench/niid_bench/client_fednova.py", line 53, in get_parameters\n    return [val.cpu().numpy() for val in self.net.parameters()]\n  File "/media/namvq/Data/code_flwr/niid_bench/niid_bench/client_fednova.py", line 53, in <listcomp>\n    return [val.cpu().numpy() for val in self.net.parameters()]\nRuntimeError: Can\'t call numpy() on Tensor that requires grad. Use tensor.detach().numpy() instead.\n',)
[2024-11-23 11:20:45,530][flwr][ERROR] - [36mray::DefaultActor.run()[39m (pid=77529, ip=192.168.1.62, actor_id=33b8b395ca8c80c1c3a0779601000000, repr=<flwr.simulation.ray_transport.ray_actor.DefaultActor object at 0x7cbd7010f100>)
  File "/home/namvq/.cache/pypoetry/virtualenvs/niid-bench-orV17zke-py3.10/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 179, in get_parameters
    return maybe_call_get_parameters(
  File "/home/namvq/.cache/pypoetry/virtualenvs/niid-bench-orV17zke-py3.10/lib/python3.10/site-packages/flwr/client/client.py", line 197, in maybe_call_get_parameters
    return client.get_parameters(get_parameters_ins)
  File "/home/namvq/.cache/pypoetry/virtualenvs/niid-bench-orV17zke-py3.10/lib/python3.10/site-packages/flwr/client/app.py", line 320, in _get_parameters
    parameters = self.numpy_client.get_parameters(config=ins.config)  # type: ignore
  File "/media/namvq/Data/code_flwr/niid_bench/niid_bench/client_fednova.py", line 53, in get_parameters
    return [val.cpu().numpy() for val in self.net.parameters()]
  File "/media/namvq/Data/code_flwr/niid_bench/niid_bench/client_fednova.py", line 53, in <listcomp>
    return [val.cpu().numpy() for val in self.net.parameters()]
RuntimeError: Can't call numpy() on Tensor that requires grad. Use tensor.detach().numpy() instead.

The above exception was the direct cause of the following exception:

[36mray::DefaultActor.run()[39m (pid=77529, ip=192.168.1.62, actor_id=33b8b395ca8c80c1c3a0779601000000, repr=<flwr.simulation.ray_transport.ray_actor.DefaultActor object at 0x7cbd7010f100>)
  File "/home/namvq/.cache/pypoetry/virtualenvs/niid-bench-orV17zke-py3.10/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 72, in run
    raise ClientException(str(message)) from ex
flwr.simulation.ray_transport.ray_actor.ClientException: 
>>>>>>>A ClientException occurred.('\n\tSomething went wrong when running your client workload.\n\tClient 1 crashed when the DefaultActor was running its workload.\n\tException triggered on the client side: Traceback (most recent call last):\n  File "/home/namvq/.cache/pypoetry/virtualenvs/niid-bench-orV17zke-py3.10/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 60, in run\n    job_results = job_fn()\n  File "/home/namvq/.cache/pypoetry/virtualenvs/niid-bench-orV17zke-py3.10/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 179, in get_parameters\n    return maybe_call_get_parameters(\n  File "/home/namvq/.cache/pypoetry/virtualenvs/niid-bench-orV17zke-py3.10/lib/python3.10/site-packages/flwr/client/client.py", line 197, in maybe_call_get_parameters\n    return client.get_parameters(get_parameters_ins)\n  File "/home/namvq/.cache/pypoetry/virtualenvs/niid-bench-orV17zke-py3.10/lib/python3.10/site-packages/flwr/client/app.py", line 320, in _get_parameters\n    parameters = self.numpy_client.get_parameters(config=ins.config)  # type: ignore\n  File "/media/namvq/Data/code_flwr/niid_bench/niid_bench/client_fednova.py", line 53, in get_parameters\n    return [val.cpu().numpy() for val in self.net.parameters()]\n  File "/media/namvq/Data/code_flwr/niid_bench/niid_bench/client_fednova.py", line 53, in <listcomp>\n    return [val.cpu().numpy() for val in self.net.parameters()]\nRuntimeError: Can\'t call numpy() on Tensor that requires grad. Use tensor.detach().numpy() instead.\n',)
[2024-11-23 11:20:45,530][flwr][ERROR] - Your simulation crashed :(. This could be because of several reasons.The most common are: 
	 > Your system couldn't fit a single VirtualClient: try lowering `client_resources`.
	 > All the actors in your pool crashed. This could be because: 
		 - You clients hit an out-of-memory (OOM) error and actors couldn't recover from it. Try launching your simulation with more generous `client_resources` setting (i.e. it seems {'num_cpus': 6, 'num_gpus': 0.5} is not enough for your workload). Use fewer concurrent actors. 
		 - You were running a multi-node simulation and all worker nodes disconnected. The head node might still be alive but cannot accommodate any actor with resources: {'num_cpus': 6, 'num_gpus': 0.5}.
